export enum ContantsNavigator {
    SPLASH_SCREEN = 'SPLASH_SCREEN',
    WELCOME_SCREEN = 'WELCOME_SCREEN',

    HOME_SCREEN = 'HOME_SCREEN',

    MAIN_STATE = 'MAIN_STATE',
    AUTHENTICATION_STATE = 'AUTHENTICATION_STATE',

    //AUTH
    LOGIN_SCREEN = 'LOGIN_SCREEN'
}