export enum ContantsNavigator {
    SPLASH_SCREEN = 'SPLASH_SCREEN',
    ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',

    HOME_SCREEN = 'HOME_SCREEN',

    MAIN_STATE = 'MAIN_STATE',
    AUTHENTICATION_STATE = 'AUTHENTICATION_STATE',

    //AUTH
    LOGIN_SCREEN = 'LOGIN_SCREEN',
    REGISTER_SCREEN = 'REGISTER_SCREEN',
    VERTIFICATION_CODE_SCREEN = 'VERTIFICATION_CODE_SCREEN',
    FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',
    VERIFIRED_SUCCESS_SCREEN = 'VERIFIRED_SUCCESS_SCREEN',
    OTP_CODE_FORGOT_SCREEN = 'OTP_CODE_FORGOT_SCREEN',
    RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN'
}